apiVersion: v1
kind: Service
metadata:
  name: geode-0
  labels:
    app: geode
spec:
  type: NodePort
  selector:
    app: geode
  ports:
  - port: 10334
    targetPort: 10334
    name: locator
  - port: 10100
    targetPort: 10100
    name: data-node
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geode
spec:
  serviceName: "geode"
  replicas: 1
  selector:
    matchLabels:
      app: geode
  template:
    metadata:
      labels:
        app: geode
    spec:
      containers:
      - name: locator
        image: apache-geode-locator:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 10334
          name: locator
      - name: data-node
        image: apache-geode-data-node:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 10100
          name: data-node
        readinessProbe:
          tcpSocket:
            port: 10100
        livenessProbe:
          tcpSocket:
            port: 10100